name = "Benchmarks"
uuid = "ee90295e-6669-4bb8-a4cc-7a75c3f9c67d"
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"
