[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"

[sources]
Oceananigans = {path = ".."}
