include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:bionic

julia:1.4:unit:
  extends:
    - .julia:1.4
    - .test
  variables:
    TEST_GROUP: 'unit'
  tags:
    - nvidia

julia:1.4:integration:
  extends:
    - .julia:1.4
    - .test
  variables:
    TEST_GROUP: 'model'
  tags:
    - nvidia

julia:1.4:integration:
  extends:
    - .julia:1.4
    - .test
  variables:
    TEST_GROUP: 'simulation'
  tags:
    - nvidia


julia:1.4:regression:
  extends:
    - .julia:1.4
    - .test
  variables:
    TEST_GROUP: 'regression'
  tags:
    - nvidia

julia:1.4:scripts:
  extends:
    - .julia:1.4
    - .test
  variables:
    TEST_GROUP: 'scripts'
  tags:
    - nvidia

coverage:
  extends:
    - .julia:1.4
    - .coverage
