variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/test.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/coverage.yml'

test:v1.1:
  extends: .test:v1.1

test:v1.2:
  extends: .test:v1.2

test:v1.3:
  extends: .test:v1.3

test:dev:
  extends: .test:dev
  allow_failure: true
