language: julia

os:
  - osx

julia:
  - 1.5

env:
  jobs:
    - TEST_GROUP=unit
    - TEST_GROUP=time_stepping_1
    - TEST_GROUP=time_stepping_2
    - TEST_GROUP=simulation
    - TEST_GROUP=regression
    - TEST_GROUP=scripts
  global:
    - PYTHON=''

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - travis_wait 45 julia --project=docs/ docs/make.jl
      after_success: skip
