site_name:        Oceananigans.jl
repo_url:         https://github.com/ali-ramadhan/Oceananigans.jl
site_description: Documentation for Oceananigans.jl
site_author:      Ali Ramadhan
theme:            readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

nav:
  - Home: index.md
